name: Dispatch to ExampleProject_GitActions

on:
  push:
    branches: [ master ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to target repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: AlexAksioma/ExampleProject_GitActions
          event-type: external-push